name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: debug
      run: |
        dig sftp
        cat /etc/resolv.conf
        cat /etc/sysconfig/docker      
    - name: yarn install, build, and test
      run: |
        yarn
        yarn test
      env:
        CI: true
        SFTP_HOST: sftp.localhost
        SFTP_PORT: 22

    services:
       sftp:
        image: atmoz/sftp      
