name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run sftp image
      run: |
          /usr/bin/docker run -d  -p 2222:22  -e "SFTP_USERS=sftp:sftp:::upload" -e GITHUB_ACTIONS=true -e CI=true -v "/$(pwd)/test/__fixtures__/samples":"/home/sftp/samples" atmoz/sftp
          sleep 10

    - name: yarn install, build, and test
      run: |
        yarn
        yarn test
      env:
        CI: true
        SFTP_HOST: 127.0.0.1
        SFTP_PORT: ${{ job.services.localsftp.ports[2222] }}
